POST http://127.0.0.1:8080/appium/sendtext
Content-Type: application/json

{
  "userId":  "65d52255bab42ab9b19d587a",
  "messageToSend" : "My guess would be you hate it"


}

###
POST http://127.0.0.1:8080/appium/refreshUserMessage
Content-Type: application/json

{
  "userId":  "65d168b8e5e69003db90d73a"
}

###
POST http://127.0.0.1:8080/ai/updatePrompt
Content-Type: application/json

{
  "updatedPrompt":  "SomeUpdated promptCheck"
}

###
POST http://104.42.212.81:8080/appium/refreshUserMessage
Content-Type: application/json

{
  "userId":  "65d168b8e5e69003db90d73a"
}

###
POST http://127.0.0.1:8080/runautoscraper
Content-Type: application/json

{}

###
GET http://127.0.0.1:8080/appium
Accept: application/json

###
GET http://127.0.0.1:8080/checkasync
Accept: application/json

###
GET http://127.0.0.1:8080/user/65b97a812d5ee8a9173907d4
Accept: application/json

###
GET http://127.0.0.1:8080/ai/refreshmessages/65d168b8e5e69003db90d73a
Accept: application/json

###
GET http://127.0.0.1:8080/ai/user/65d52255bab42ab9b19d587a
Accept: application/json

###
GET http://104.42.212.81:8080/ai/user/65d52255bab42ab9b19d587a
Accept: application/json

###
GET http://127.0.0.1:8080/ai/notifications
Accept: application/json

###
GET http://127.0.0.1:8080
Accept: application/json

###
GET http://104.42.212.81:8080
Accept: application/json

###
GET http://127.0.0.1:8080/getLastUpdated
Accept: application/json

###
GET http://104.42.212.81:8080/getLastUpdated
Accept: application/json

###
GET http://104.42.212.81:8080/user/65c13a1535045765257fe90c
Accept: application/json
