GET http://127.0.0.1:5000/appium
Accept: application/json

###
GET http://127.0.0.1:5000/user/65b97b812d5ee8a9173907ec
Accept: application/json

###
GET http://127.0.0.1:5000
Accept: application/json

###
